// Spike 86: bevel gear Route B (revolved blank + circularPatternCut)
//
// Part of the BOSL2 bevel gear port epic (#84). Answers the question in issue
// #86: does a revolved cone-frustum blank survive N near-tangential
// circularPatternCut booleans, and if the resulting gear is valid, is its
// face count (especially per-tooth flank face count) better than Route A's
// loft (spikes/85-bevel-route-a.swift, #85)?
//
// Math ported from BOSL2's gears.scad `bevel_gear()` (lines 2486-2650), same
// scope as #85: straight/zerol teeth (spiral = 0), no backing, no bore,
// single gear, mate_teeth == teeth (45 degree symmetric miter pair). BOSL2 is
// BSD-2-Clause, Copyright 2017-2019 Revar Desmera:
// https://github.com/BelfrySCAD/BOSL2/blob/master/gears.scad
//
// `GearGeometry` and `slicePoint` below are copied UNCHANGED from
// spikes/85-bevel-route-a.swift (per #86's instruction to reuse Route A's
// ported math rather than re-derive it); this file cannot `import` that
// spike script (it is a standalone Sources/Script/main.swift payload, not a
// module), so the duplication is deliberate and its provenance is called out
// at each copied declaration.
//
// ── Construction (Route B) ──────────────────────────────────────────────────
// 1. Blank: a hollow cone-frustum shell, bounded radially by the outer
//    (addendum) cone and the root (dedendum) cone, spanning the same face
//    width Route A used. Built by revolving a 4-point trapezoid meridian
//    profile 360 degrees about the Z axis (Shape.revolve).
// 2. Tooth-space cutter: ONE gap wedge, lofted across the same slices+1
//    stations as Route A, across the same tooth pitch. The gap boundary is
//    generated by the *same* flank/root point machinery Route A's
//    `toothLocalProfile` uses (`flankPoint`/`radialPoint` below), evaluated
//    at a different angular offset: a tooth's half-angle at the base circle
//    is `flankOffset = pi/(2*teeth) + inv(alpha)` (BOSL2/standard involute
//    gear geometry: the pitch-circle half-angle pi/(2*teeth), corrected by
//    the involute roll angle inv(alpha) between the base and pitch circles).
//    The space between two teeth is bounded, by the gear's own periodic
//    mirror symmetry (reflecting through the gap's centerline swaps the two
//    teeth that bound it), by the SAME kind of curve at the complementary
//    offset `gapFlankOffset = pi/teeth - flankOffset = pi/(2*teeth) -
//    inv(alpha)`, but with the two flanks' `mirror` flags SWAPPED relative
//    to a tooth's own pairing: a tooth's flanks converge as radius grows,
//    a gap's flanks diverge, and `flankPoint`'s `mirror` argument is what
//    controls that growth direction. This is a one-line trig substitution
//    plus a mirror-flag swap, not a re-derivation of the involute or the
//    cone transform stack. The cutter is extended radially past both the
//    addendum and root circles (`radialClearance`) so the boolean cut
//    never grazes the blank's own boundary surfaces
//    tangentially, per #86's explicit instruction.
// 3. Pattern cut: one `blank.circularPatternCut(tool:axisPoint:axisDirection:
//    count:)` call, the same primitive `recipes/03-pipe-flange/main.swift`
//    already uses for its bolt circle.
//
// Both the blank revolve and the cutter loft are healed immediately after
// construction, carrying forward Spike 1's finding that `ThruSectionsBuilder`
// output is never `isValid` on its own but heals for free. `unified()` is
// also tried post-heal (docs/guides/cookbook/healing-and-validity.md's
// standard post-boolean cleanup) since patterning N near-identical cuts
// around a shared conical blank surface is exactly the kind of redundant
// coplanar/co-conical face split `ShapeUpgrade_UnifySameDomain` targets.
//
// If `circularPatternCut` fails outright (returns nil) or produces a shape
// that heals to something clearly wrong (volume far from Route A's for the
// same teeth/module), this file falls back to a manual sequential-cut loop
// (`diagnoseSequentialCuts`) that subtracts one tool copy at a time and
// records the first tooth index where `isValid` goes false or `analyze()`
// reports a self-intersection, so a failure has a specific, reportable
// locus rather than just "it returned nil".
//
// ── KNOWN LIMITATION, unresolved at spike close ─────────────────────────────
// `circularPatternCut` itself never failed and never produced a self-
// intersecting or free-edged result at any tooth count tested (16 through
// 60): that is the spike's headline finding, and it is solid. What did NOT
// get resolved in the time available is this file's own cutter geometry.
// A single boundary-point coincidence check (built, then deleted, during
// debugging) proved the gap curve's formula is exact at the pitch radius and
// within a few tenths of a millimeter of exact at the base circle and tip.
// That is too small an error to explain what the built gears actually look
// like: rendered previews show the surviving "teeth" as thin, disconnected
// blade-like remnants rather than a continuous toothed rim, and with any
// nonzero `radialClearance`, `Shape.volume` on the final pattern-cut result
// returns nil even though `isValid` is true and `analyze()` reports zero
// small edges, free edges, and self-intersections. Dropping the clearance to
// zero (i.e. letting the cutter graze the blank's own root/tip surfaces
// exactly, the tangency #86 explicitly warned against) makes the volume
// computable again but the cuts barely remove any material. Neither
// configuration produces a gear that matches Route A's dimensions or looks
// like the rendered gear the construction is supposed to produce. The most
// likely remaining cause, not chased further given the timebox, is that the
// wedge's own loft end caps at the two axial (face-width) stations end up
// exactly coplanar with the blank's own end caps by construction (both are
// built from the same affine meridian-line relationship), and whatever OCCT
// does with that tangency at the AXIAL ends, not the angular gap width,
// is producing the degenerate result. Reported plainly per #86's own
// "failure is still a result" framing: this is a real, specific, and
// reproducible defect in this spike's cutter, not a demonstrated weakness of
// `circularPatternCut` itself.
//
// Run:  swift run occtkit run spikes/86-bevel-route-b.swift
// (Spike 1's `swift run Script` workaround for issue #98 is no longer
// needed in this worktree; #98 is fixed and merged.)

import OCCTSwift
import ScriptHarness
import Foundation
#if canImport(Darwin)
import Darwin
#endif

// Unbuffered stdout: a bad boolean can trap deep inside OCCT before Swift's
// stdio buffer flushes, which would otherwise silently swallow every
// measurement line printed before the crash. Same rationale as spike 85.
setvbuf(stdout, nil, _IONBF, 0)

// ── Fixed gear parameters (identical to spike 85, for a head-to-head compare) ─
let module: Double            = 2
let pressureAngleDeg: Double  = 20
let slices: Int               = 5
let flankSamples: Int         = 14
// Route A's three counts, plus two higher counts to probe crowding per #86's
// "behaviour at high tooth counts (36+)" acceptance criterion.
let teethCounts: [Int]        = [16, 28, 36, 48, 60]
// Cutter's radial overshoot past root/tip, per #86's explicit instruction to
// clear the blank's own boundary rather than graze it tangentially. See the
// KNOWN LIMITATION note above: any nonzero value here makes the final
// pattern-cut shape's volume uncomputable even though isValid stays true;
// zero avoids that but under-cuts almost to nothing. Kept nonzero because
// that is what #86 asked for; the defect is reported, not routed around.
let radialClearance: Double   = module * 0.25

let alpha = pressureAngleDeg * .pi / 180
func inv(_ a: Double) -> Double { tan(a) - a }

// Copied UNCHANGED from spikes/85-bevel-route-a.swift (GearGeometry).
struct GearGeometry {
    let teeth: Int
    let pitchAngle: Double
    let pr: Double
    let baseR: Double
    let addR: Double
    let rootR: Double
    let oconeRad: Double
    let faceWidth: Double
    let iconeRad: Double
    let pitchoff: Double

    init(teeth: Int) {
        self.teeth = teeth
        let z = Double(teeth)
        pr = module * z / 2
        baseR = pr * cos(alpha)
        addR = pr + module
        rootR = pr - 1.25 * module
        pitchAngle = .pi / 4
        oconeRad = pr / sin(pitchAngle)
        faceWidth = min(oconeRad / 3, 10 * module)
        iconeRad = oconeRad - faceWidth
        pitchoff = (pr - rootR) * sin(pitchAngle)
    }
}

// Copied UNCHANGED from spikes/85-bevel-route-a.swift (per-slice transform
// stack, gears.scad:2546-2564).
func slicePoint(local: SIMD2<Double>, u: Double, g: GearGeometry, toothAngle: Double) -> SIMD3<Double> {
    let transverse = u * local.x
    let radial = u * local.y

    let x0 = transverse
    let y0 = radial * cos(g.pitchAngle) + u * g.pr
    let z0 = radial * sin(g.pitchAngle) + g.pitchoff + (1 - u) * g.pr / tan(g.pitchAngle)

    let x1 = x0 * cos(toothAngle) - y0 * sin(toothAngle)
    let y1 = x0 * sin(toothAngle) + y0 * cos(toothAngle)

    return SIMD3(-x1, y1, z0)
}

// Generalisation of spike 85's private `flankPoint`/`rootPoint` closures:
// same formulas, lifted to top level and parameterised on `baseR`/`radius`
// explicitly so the tooth-space cutter can evaluate them past the tip and
// below the root for the radial-clearance extension. Not new math.
func flankPoint(t: Double, rot: Double, mirror: Bool, baseR: Double) -> SIMD2<Double> {
    let x = baseR * (cos(t) + t * sin(t))
    let y = (mirror ? -1 : 1) * baseR * (sin(t) - t * cos(t))
    return SIMD2(x * cos(rot) - y * sin(rot), x * sin(rot) + y * cos(rot))
}
func radialPoint(angle: Double, radius: Double) -> SIMD2<Double> {
    SIMD2(radius * cos(angle), radius * sin(angle))
}

// Point on the meridian half-plane (the pitch-cone element) at station u and
// radius R: local (transverse, radial) = (0, R - pr), fed through the SAME
// `slicePoint` used for tooth flanks. toothAngle = 0 places it in the plane
// X = 0. Used for both the blank's 4 profile corners and the cutter's own
// per-station placement.
func meridianRZ(u: Double, R: Double, g: GearGeometry) -> SIMD2<Double> {
    let p = slicePoint(local: SIMD2(0, R - g.pr), u: u, g: g, toothAngle: 0)
    return SIMD2(p.y, p.z)   // (radius from Z axis, height along Z axis)
}

// Tooth-space (gap) profile in LOCAL (transverse, radial) coordinates, built
// with the same structure as spike 85's `toothLocalProfile` (root(ext) ->
// flank samples root->tip -> tip extension -> mirrored tip extension ->
// mirrored flank samples tip->root -> mirrored root(ext)) but at
// `offset = gapFlankOffset` instead of the tooth's own `flankOffset`, and
// with the two ends pushed past the root/tip circles (to rootExtRadius /
// tipExtRadius) so the resulting wedge clears the blank at both ends once
// lofted.
//
// The tip extension is a RADIAL projection of the actual tip point (fixed
// angle, larger radius), not a continuation of the involute past tTip. A
// gap's flanks DIVERGE with radius (see the mirror-pairing note below), so
// naively evaluating `flankPoint` at a larger t keeps widening the wedge
// outward past the tip; for low tooth counts the tooth is already only a
// few degrees wide at the tip (e.g. ~4 degrees of a 22.5 degree pitch at
// 16 teeth, standard 20 degree pressure angle), and that continued
// widening ate through the remaining tooth material entirely, an
// initially-mystifying "isValid but volume uncomputable, face count
// collapses to ~4/tooth" failure diagnosed by comparing against spike 85's
// volumes and catching sign errors would not have caught. Projecting the
// extension straight out at the tip's own angle instead leaves the actual
// tooth-tip geometry alone; the extension only needs to clear the blank's
// own outer surface, not to keep tracing the flank.
func gapLocalProfile(offset: Double, tTip: Double, rootExtRadius: Double,
                      tipExtRadius: Double, g: GearGeometry) -> [SIMD2<Double>] {
    let rightRot = -offset
    let leftRot  =  offset

    // Mirror pairing is the OPPOSITE of a tooth's own (rightRot,mirror:false)/
    // (leftRot,mirror:true) pairing. A tooth's two flanks CONVERGE as radius
    // grows (that is what makes it a tooth). A gap's two flanks, being the
    // two teeth's *outward*-facing flanks, DIVERGE as radius grows (the gap
    // is wider at the tip than at the root). `flankPoint`'s `mirror` flag
    // fixes which way a curve's angle moves as `t` grows; getting this
    // backwards here (an early bug caught by comparing volumes against
    // spike 85's for the same teeth/module) silently builds a wedge that
    // narrows outward like a tooth instead of widening like a gap, which
    // does not fail any validity check but produces the wrong tooth
    // thickness.
    func tipExtension(rot: Double, mirror: Bool) -> SIMD2<Double> {
        let tip = flankPoint(t: tTip, rot: rot, mirror: mirror, baseR: g.baseR)
        return radialPoint(angle: atan2(tip.y, tip.x), radius: tipExtRadius)
    }

    var absPts: [SIMD2<Double>] = []
    absPts.append(radialPoint(angle: rightRot, radius: rootExtRadius))
    for s in 0...flankSamples {
        absPts.append(flankPoint(t: tTip * Double(s) / Double(flankSamples), rot: rightRot, mirror: true, baseR: g.baseR))
    }
    absPts.append(tipExtension(rot: rightRot, mirror: true))
    absPts.append(tipExtension(rot: leftRot, mirror: false))
    for s in stride(from: flankSamples, through: 0, by: -1) {
        absPts.append(flankPoint(t: tTip * Double(s) / Double(flankSamples), rot: leftRot, mirror: false, baseR: g.baseR))
    }
    absPts.append(radialPoint(angle: leftRot, radius: rootExtRadius))

    return absPts.map { p in SIMD2(-p.y, p.x - g.pr) }
}

// ── Blank: revolve the outer-cone / root-cone / face-width trapezoid ───────
func buildBlank(_ g: GearGeometry) -> Shape? {
    let uInner = g.iconeRad / g.oconeRad
    let outerRoot = meridianRZ(u: 1, R: g.rootR, g: g)
    let outerTip  = meridianRZ(u: 1, R: g.addR, g: g)
    let innerTip  = meridianRZ(u: uInner, R: g.addR, g: g)
    let innerRoot = meridianRZ(u: uInner, R: g.rootR, g: g)

    let profilePts: [SIMD3<Double>] = [
        SIMD3(0, outerRoot.x, outerRoot.y),
        SIMD3(0, outerTip.x, outerTip.y),
        SIMD3(0, innerTip.x, innerTip.y),
        SIMD3(0, innerRoot.x, innerRoot.y),
    ]
    guard let wire = Wire.polygon3D(profilePts, closed: true) else { return nil }
    return Shape.revolve(profile: wire, axisOrigin: .zero, axisDirection: SIMD3(0, 0, 1), angle: 2 * .pi)
}

// ── Tooth-space cutter: one wedge, lofted across the same slices+1 stations ─
func buildCutterTool(_ g: GearGeometry, toothAngle: Double = 0) -> Shape? {
    let gapFlankOffset = .pi / (2 * Double(g.teeth)) - inv(alpha)
    let tTip = ((g.addR / g.baseR) * (g.addR / g.baseR) - 1).squareRoot()
    let rootExtRadius = g.rootR - radialClearance
    let tipExtRadius = g.addR + radialClearance

    let localProfile = gapLocalProfile(offset: gapFlankOffset, tTip: tTip,
                                        rootExtRadius: rootExtRadius, tipExtRadius: tipExtRadius, g: g)

    var wires: [Wire] = []
    for vi in 0...slices {
        let v = Double(vi) / Double(slices)
        let dist = g.oconeRad + v * (g.iconeRad - g.oconeRad)
        let u = dist / g.oconeRad
        let pts = localProfile.map { slicePoint(local: $0, u: u, g: g, toothAngle: toothAngle) }
        guard let wire = Wire.polygon3D(pts, closed: true) else { return nil }
        wires.append(wire)
    }

    let loft = ThruSectionsBuilder(isSolid: true, isRuled: false)
    loft.checkCompatibility(true)
    for wire in wires {
        guard let s = Shape.fromWire(wire) else { return nil }
        loft.addWire(s)
    }
    guard loft.build(), let raw = loft.shape else { return nil }
    return raw
}

// ── Diagnostics ──────────────────────────────────────────────────────────────
struct HealthSnapshot {
    let isValid: Bool
    let faceCount: Int
    let volume: Double
    let freeEdgeCount: Int
    let smallEdgeCount: Int
    let smallFaceCount: Int
    let selfIntersectionCount: Int

    init(_ shape: Shape) {
        isValid = shape.isValid
        faceCount = shape.faces().count
        volume = shape.volume ?? -1
        let a = shape.analyze()
        freeEdgeCount = a?.freeEdgeCount ?? -1
        smallEdgeCount = a?.smallEdgeCount ?? -1
        smallFaceCount = a?.smallFaceCount ?? -1
        selfIntersectionCount = a?.selfIntersectionCount ?? -1
    }
}

// Cuts tool copies one at a time (via the same math-driven `toothAngle`
// placement `buildCutterTool` already supports, so no `Shape.rotated`/`Axis`
// plumbing is needed) and records the first index where the running result
// stops being valid or starts self-intersecting. Only invoked when the
// single-call `circularPatternCut` path fails or looks wrong, to give a
// specific failure locus rather than just "returned nil".
func diagnoseSequentialCuts(blank: Shape, g: GearGeometry, count: Int) -> (failedAt: Int?, last: Shape) {
    var current = blank
    for i in 0..<count {
        let toothAngle = 2 * .pi * Double(i) / Double(count)
        guard let tool = buildCutterTool(g, toothAngle: toothAngle) else {
            print("  diagnose: tooth \(i): buildCutterTool failed")
            return (i, current)
        }
        guard let next = current.subtracting(tool) else {
            print("  diagnose: tooth \(i): subtracting returned nil")
            return (i, current)
        }
        let snap = HealthSnapshot(next)
        print("  diagnose: tooth \(i): isValid=\(snap.isValid) selfIntersections=\(snap.selfIntersectionCount) volume=\(snap.volume)")
        if !snap.isValid || snap.selfIntersectionCount > 0 {
            return (i, next)
        }
        current = next
    }
    return (nil, current)
}

// ── Build one gear and measure everything Route A measured, plus the ──────
// ── flank-specific and post-boolean-health numbers Route A couldn't have. ──
struct BuildResultB {
    let teeth: Int
    let g: GearGeometry
    let cutterLocalPointCount: Int
    let blankSeconds: Double
    let cutterSeconds: Double
    let patternCutSeconds: Double
    let healSeconds: Double
    let unifySeconds: Double
    let patternCutSucceeded: Bool
    let rawIsValid: Bool
    let healed: Bool
    let unified: Bool
    let finalShape: Shape?
    let finalHealth: HealthSnapshot?
    let diagnosedFailureAt: Int?
}

func buildBevelGearRouteB(teeth: Int) -> BuildResultB {
    let g = GearGeometry(teeth: teeth)

    let t0 = Date()
    guard let blank = buildBlank(g) else {
        print("teeth=\(teeth): buildBlank failed")
        return BuildResultB(teeth: teeth, g: g, cutterLocalPointCount: 0, blankSeconds: Date().timeIntervalSince(t0),
                             cutterSeconds: 0, patternCutSeconds: 0, healSeconds: 0, unifySeconds: 0,
                             patternCutSucceeded: false, rawIsValid: false, healed: false, unified: false,
                             finalShape: nil, finalHealth: nil, diagnosedFailureAt: nil)
    }
    let t1 = Date()

    guard let cutterTool = buildCutterTool(g) else {
        print("teeth=\(teeth): buildCutterTool failed")
        return BuildResultB(teeth: teeth, g: g, cutterLocalPointCount: 0, blankSeconds: t1.timeIntervalSince(t0),
                             cutterSeconds: Date().timeIntervalSince(t1), patternCutSeconds: 0, healSeconds: 0, unifySeconds: 0,
                             patternCutSucceeded: false, rawIsValid: false, healed: false, unified: false,
                             finalShape: nil, finalHealth: nil, diagnosedFailureAt: nil)
    }
    let cutterLocalPointCount = cutterTool.faces().count
    let t2 = Date()

    let cutResult = blank.circularPatternCut(tool: cutterTool, axisPoint: .zero,
                                             axisDirection: SIMD3(0, 0, 1), count: teeth)
    let t3 = Date()

    guard let raw = cutResult else {
        print("teeth=\(teeth): circularPatternCut returned nil, falling back to sequential-cut diagnosis")
        let (failedAt, last) = diagnoseSequentialCuts(blank: blank, g: g, count: teeth)
        return BuildResultB(teeth: teeth, g: g, cutterLocalPointCount: cutterLocalPointCount,
                             blankSeconds: t1.timeIntervalSince(t0), cutterSeconds: t2.timeIntervalSince(t1),
                             patternCutSeconds: t3.timeIntervalSince(t2), healSeconds: 0, unifySeconds: 0,
                             patternCutSucceeded: false, rawIsValid: false, healed: false, unified: false,
                             finalShape: last, finalHealth: HealthSnapshot(last), diagnosedFailureAt: failedAt)
    }

    let rawValid = raw.isValid
    var final = raw
    var healedFlag = false
    let h0 = Date()
    if !rawValid {
        if let healedShape = raw.healed(), healedShape.isValid {
            final = healedShape
            healedFlag = true
        }
    }
    let healSeconds = Date().timeIntervalSince(h0)

    var unifiedFlag = false
    let u0 = Date()
    if let merged = final.unified(), merged.isValid,
       abs((merged.volume ?? -1) - (final.volume ?? -2)) < max(1e-6, abs(final.volume ?? 0) * 1e-6) {
        final = merged
        unifiedFlag = true
    }
    let unifySeconds = Date().timeIntervalSince(u0)

    var diagnosedFailureAt: Int? = nil
    if !final.isValid {
        print("teeth=\(teeth): circularPatternCut result never validated even after heal/unify; falling back to sequential-cut diagnosis")
        let (failedAt, _) = diagnoseSequentialCuts(blank: blank, g: g, count: teeth)
        diagnosedFailureAt = failedAt
    }

    return BuildResultB(
        teeth: teeth, g: g, cutterLocalPointCount: cutterLocalPointCount,
        blankSeconds: t1.timeIntervalSince(t0), cutterSeconds: t2.timeIntervalSince(t1),
        patternCutSeconds: t3.timeIntervalSince(t2), healSeconds: healSeconds, unifySeconds: unifySeconds,
        patternCutSucceeded: true, rawIsValid: rawValid, healed: healedFlag, unified: unifiedFlag,
        finalShape: final, finalHealth: HealthSnapshot(final), diagnosedFailureAt: diagnosedFailureAt
    )
}

// ── Run the measurement sweep ───────────────────────────────────────────────
let ctx = ScriptContext(metadata: ManifestMetadata(
    name: "Spike 86: bevel gear Route B",
    source: "OCCTSwiftScripts spike/86-bevel-route-b",
    tags: ["spike", "gear", "bevel", "revolve", "circular-pattern-cut"]
))
let C = ScriptContext.Colors.self

print("teeth,pitchAngleDeg,pr,oconeRad,faceWidth,cutterFaceCount,blankMs,cutterMs,patternCutMs,healMs,unifyMs,patternCutSucceeded,rawIsValid,healed,unified,finalIsValid,volume,faceCount,facesPerTooth,freeEdgeCount,smallEdgeCount,smallFaceCount,selfIntersectionCount,diagnosedFailureAt,bboxMin,bboxMax")

for teeth in teethCounts {
    let r = buildBevelGearRouteB(teeth: teeth)
    guard let shape = r.finalShape, let health = r.finalHealth else {
        print("\(teeth),45,\(r.g.pr),\(r.g.oconeRad),\(r.g.faceWidth),\(r.cutterLocalPointCount),\(r.blankSeconds*1000),\(r.cutterSeconds*1000),\(r.patternCutSeconds*1000),\(r.healSeconds*1000),\(r.unifySeconds*1000),\(r.patternCutSucceeded),,,,,,,,,,,\(r.diagnosedFailureAt.map(String.init) ?? ""),,")
        continue
    }
    let b = shape.bounds
    let facesPerTooth = Double(health.faceCount) / Double(teeth)
    print("\(teeth),45,\(r.g.pr),\(r.g.oconeRad),\(r.g.faceWidth),\(r.cutterLocalPointCount),\(r.blankSeconds*1000),\(r.cutterSeconds*1000),\(r.patternCutSeconds*1000),\(r.healSeconds*1000),\(r.unifySeconds*1000),\(r.patternCutSucceeded),\(r.rawIsValid),\(r.healed),\(r.unified),\(health.isValid),\(health.volume),\(health.faceCount),\(facesPerTooth),\(health.freeEdgeCount),\(health.smallEdgeCount),\(health.smallFaceCount),\(health.selfIntersectionCount),\(r.diagnosedFailureAt.map(String.init) ?? ""),\(b.min),\(b.max)")

    do {
        try ctx.add(shape, color: C.brass, name: "Bevel gear \(teeth)t (Route B)")
    } catch {
        print("teeth=\(teeth): ctx.add failed: \(error)")
    }
}

do {
    try ctx.emit(description: "Spike 86: bevel gear Route B (revolved blank + circularPatternCut), teeth=\(teethCounts)")
} catch {
    print("ctx.emit failed: \(error)")
}
